//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClicksAndDrive.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourse_BG_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourse_BG_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClicksAndDrive.Common.Resourse.BG.", typeof(Resourse_BG_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматична.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Велосипед.
        /// </summary>
        public static string Bicycle {
            get {
                return ResourceManager.GetString("Bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на велосипеда.
        /// </summary>
        public static string BicycleSize {
            get {
                return ResourceManager.GetString("BicycleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип на велосипеда.
        /// </summary>
        public static string BicycleType {
            get {
                return ResourceManager.GetString("BicycleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автобомобил.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string CarCategory {
            get {
                return ResourceManager.GetString("CarCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места.
        /// </summary>
        public static string CarPlace {
            get {
                return ResourceManager.GetString("CarPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кросов.
        /// </summary>
        public static string Cross {
            get {
                return ResourceManager.GetString("Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описанието трябва да бъде не по-дълго от 250 символа..
        /// </summary>
        public static string DESCRIPTION_LENGHT {
            get {
                return ResourceManager.GetString("DESCRIPTION_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизел.
        /// </summary>
        public static string Diesel {
            get {
                return ResourceManager.GetString("Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електрически.
        /// </summary>
        public static string Electric {
            get {
                return ResourceManager.GetString("Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електрически скутер.
        /// </summary>
        public static string ELectricScooter {
            get {
                return ResourceManager.GetString("ELectricScooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разход на гориво.
        /// </summary>
        public static string FuelConsumtpion {
            get {
                return ResourceManager.GetString("FuelConsumtpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид гориво.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Газ.
        /// </summary>
        public static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бензин.
        /// </summary>
        public static string Gasoline {
            get {
                return ResourceManager.GetString("Gasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хечбек.
        /// </summary>
        public static string HatchBack {
            get {
                return ResourceManager.GetString("HatchBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избрали сте твърде голям файл..
        /// </summary>
        public static string IMAGE_LARGE_FILE {
            get {
                return ResourceManager.GetString("IMAGE_LARGE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избрали сте грешен файлов формат. Моля качете файл във формат (.jpg, .jpeg, .png , .gif)..
        /// </summary>
        public static string IMAGE_WRONG_FILE_NAME {
            get {
                return ResourceManager.GetString("IMAGE_WRONG_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличност.
        /// </summary>
        public static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Л.
        /// </summary>
        public static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to М.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка.
        /// </summary>
        public static string Made {
            get {
                return ResourceManager.GetString("Made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марката трябва да започва с главна буква..
        /// </summary>
        public static string MADE_UPPER_LETTER {
            get {
                return ResourceManager.GetString("MADE_UPPER_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ръчна.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимална скорост.
        /// </summary>
        public static string MaximumSpeed {
            get {
                return ResourceManager.GetString("MaximumSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег.
        /// </summary>
        public static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модел.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мотор.
        /// </summary>
        public static string Motorcycle {
            get {
                return ResourceManager.GetString("Motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string MotorcycleType {
            get {
                return ResourceManager.GetString("MotorcycleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планински.
        /// </summary>
        public static string Mountain {
            get {
                return ResourceManager.GetString("Mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете положително число..
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена на час.
        /// </summary>
        public static string PriceForHour {
            get {
                return ResourceManager.GetString("PriceForHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително..
        /// </summary>
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шосеен.
        /// </summary>
        public static string Road {
            get {
                return ResourceManager.GetString("Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скутер.
        /// </summary>
        public static string Scooter {
            get {
                return ResourceManager.GetString("Scooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Седан.
        /// </summary>
        public static string Sedan {
            get {
                return ResourceManager.GetString("Sedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на гумите.
        /// </summary>
        public static string SizeOfTires {
            get {
                return ResourceManager.GetString("SizeOfTires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорости.
        /// </summary>
        public static string Speeds {
            get {
                return ResourceManager.GetString("Speeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоростите трябва да са в интервала (0 - 30)..
        /// </summary>
        public static string SPEEDS_RANGE {
            get {
                return ResourceManager.GetString("SPEEDS_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спортен.
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размерът на гумите трябва да е в интервала (10 - 30)..
        /// </summary>
        public static string TIRE_SIZE_RANGE {
            get {
                return ResourceManager.GetString("TIRE_SIZE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоростна кутия.
        /// </summary>
        public static string TransmissionType {
            get {
                return ResourceManager.GetString("TransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Градски.
        /// </summary>
        public static string Trekking {
            get {
                return ResourceManager.GetString("Trekking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ван.
        /// </summary>
        public static string Van {
            get {
                return ResourceManager.GetString("Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превозно средство.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ХЛ.
        /// </summary>
        public static string XL {
            get {
                return ResourceManager.GetString("XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ХС.
        /// </summary>
        public static string XS {
            get {
                return ResourceManager.GetString("XS", resourceCulture);
            }
        }
    }
}
